version: '3.8'

services:
  app:
    image: wachtelhund/assignment-api:latest
    environment:
      MONGO_URI: mongodb://root:example@mongodb:27017
      PORT: 3000

    ports:
      - "3000:3000"
    depends_on: 
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
